# Generated by Django 4.1 on 2022-08-17 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='profileimage',
            new_name='image',
        ),
    ]
